### ISSUE TITLE
Request for some files

### ISSUE THREAD

**Issue by Yingshu-Li** [ChantalMP/Rad-ReStruct#1]
Hi,

First, thank you for your sharing. I found that the structured reports, in 'new_reports', and the QA pairs, in '_qa_pairs' cannot be found in the data file. Where can I find these files?

Thank you.

**Comment by ChantalMP** [comment]
Hi,

thanks for reaching out :) I uploaded the respective files, they should now be in the data/radrestruct/ directory.

Best,
Chantal
