### ISSUE TITLE
Multiple GPUs Training Error

### ISSUE THREAD

**Issue by Pyy-hah** [ChantalMP/Rad-ReStruct#2]
Thank you for sharing. When I was training on the Rad-ReStruct dataset using multiple GPUs, I encountered an issue that resulted in being able to use only one GPU for training. However, using multiple GPUs on the VQA-RAD dataset posed no problems. All library versions are the same as those in the requirements.txt file.
This is the error I'm getting when using multiple GPUs in the Rad-ReStruct dataset:

> 
> Layer (type:depth-idx)                                                 Param #
> 
> ModelWrapper                                          
> ├─Model: 1-1                                             
> │    └─ImageEncoderEfficientNet: 2-1        
> ... ...
> ├─BCEWithLogitsLoss: 1-2       
> 
> Total params: 162,640,528
> Trainable params: 162,640,528
> Non-trainable params: 0
> 
> Using 16bit native Automatic Mixed Precision (AMP)
> GPU available: True (cuda), used: True
> TPU available: False, using: 0 TPU cores
> IPU available: False, using: 0 IPUs
> HPU available: False, using: 0 HPUs
> Traceback (most recent call last):
>   
> 
> File "/home/zllu/anaconda3/envs/torch13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/zllu/anaconda3/envs/torch13/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/data/userdisk1/zllu/Med-VQA/hi-VQA/train/train_radrestruct.py", line 138, in <module>
>     trainer.fit(model, train_dataloaders=trainloader, val_dataloaders=valloader)
>   File "/home/zllu/anaconda3/envs/torch13/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
>     call._call_and_handle_interrupt(
>   File "/home/zllu/anaconda3/envs/torch13/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
>     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
>   File "/home/zllu/anaconda3/envs/torch13/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 113, in launch
>     mp.start_processes(
>   File "/home/zllu/anaconda3/envs/torch13/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 189, in start_processes
>     process.start()
>   File "/home/zllu/anaconda3/envs/torch13/lib/python3.9/multiprocessing/process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "/home/zllu/anaconda3/envs/torch13/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
>     return Popen(process_obj)
>   File "/home/zllu/anaconda3/envs/torch13/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
>     super().__init__(process_obj)
>   File "/home/zllu/anaconda3/envs/torch13/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
>     self._launch(process_obj)
>   File "/home/zllu/anaconda3/envs/torch13/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
>     reduction.dump(process_obj, fp)
>   File "/home/zllu/anaconda3/envs/torch13/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> 
> **AttributeError: Can't pickle local object 'ModelWrapper.__init__.<locals>.custom_collate'**

I'm not sure if it's because "custom_collate" is a custom class, causing pickle to be unable to serialize it and throwing an exception.
I'm wondering if you've encountered this situation during the training process? How would you suggest resolving this issue? Thank you for your advice!

**Comment by ChantalMP** [comment]
Hey :)
I only trained using a single GPU, therefore I did not run into this problem. It sounds like it's caused by the custom_collate function. It may be that pickle has a problem with nested functions. Maybe you can try to update the default_collate_fn_map outside of the function or even define it from scratch with all types in it. 
Otherwise, you can check if you can reformat the info object into from a dict into an object type which the default collate function can already handle and in that way get rid of the custom_collate. 

I hope one of these two options works for you.

**Comment by Pyy-hah** [comment]
Hey, thank you for your response. The following two steps can solve this issue:

1. In the "model.py" file, simply move these lines of code outside the scope of the class "ModelWrapper".

> def collate_dict_fn(batch, *, collate_fn_map):
>     return batch
> 
> def custom_collate(batch):
>     default_collate_fn_map.update({dict: collate_dict_fn})
>     return collate(batch, collate_fn_map=default_collate_fn_map)

2. In the "train_radrestruct.py" file, move these lines of code to the beginning of the file.

> ...
> from data_utils.data_radrestruct import RadReStruct
> from net.model import ModelWrapper
> 
> warnings.simplefilter("ignore", UserWarning)
> def collate_dict_fn(batch, *, collate_fn_map):
>     return batch
> 
> def custom_collate(batch):
>     default_collate_fn_map.update({dict: collate_dict_fn})
>     return collate(batch, collate_fn_map=default_collate_fn_map)
> 
> if __name__ == '__main__':
>     parser = argparse.ArgumentParser(description="Finetune on RadReStruct")
> ...

By doing this, you will be able to train using multiple GPUs.

**Comment by ChantalMP** [comment]
Perfect, happy to hear it works now :)
